server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /support {
    proxy_pass http://support-api:8000/support;
  }

  location /health {
    proxy_pass http://support-api:8000/health;
  }
}